"""add_project_id_and_name_to_llm_providers

Revision ID: 19fa42d78025
Revises: 2b3cf6131453
Create Date: 2025-10-31 18:18:37.539604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '19fa42d78025'
down_revision: Union[str, None] = '2b3cf6131453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add project_id column (nullable first)
    op.add_column('llm_providers', sa.Column('project_id', sa.Integer(), nullable=True))
    
    # For each user, create or get default project and assign existing LLMs to it
    op.execute("""
        DO $$
        DECLARE
            user_rec RECORD;
            default_project_id INTEGER;
        BEGIN
            FOR user_rec IN SELECT id FROM users LOOP
                -- Get or create default project for this user
                SELECT id INTO default_project_id 
                FROM projects 
                WHERE user_id = user_rec.id AND (name = 'Default Project' OR name LIKE '%Default Project%')
                LIMIT 1;
                
                IF default_project_id IS NULL THEN
                    -- Create default project
                    INSERT INTO projects (user_id, name, public_id)
                    VALUES (user_rec.id, 'Default Project', 'proj_' || substr(md5(random()::text), 1, 24))
                    RETURNING id INTO default_project_id;
                END IF;
                
                -- Assign existing LLMs to default project
                UPDATE llm_providers 
                SET project_id = default_project_id 
                WHERE user_id = user_rec.id AND project_id IS NULL;
            END LOOP;
        END $$;
    """)
    
    # Now make project_id non-nullable
    op.alter_column('llm_providers', 'project_id', nullable=False)
    
    # Create foreign key
    op.create_foreign_key('fk_llm_providers_project_id', 'llm_providers', 'projects', ['project_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_llm_providers_project_id', 'llm_providers', type_='foreignkey')
    op.drop_column('llm_providers', 'project_id')
    # Note: We don't drop name column as it might be needed
    # ### end Alembic commands ###

