"""add_name_to_llm_providers

Revision ID: 2b3cf6131453
Revises: 7526a4d87f04
Create Date: 2025-10-31 15:14:31.722528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3cf6131453'
down_revision: Union[str, None] = '7526a4d87f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_providers', sa.Column('name', sa.String(), nullable=False))
    # Check if avatar_url exists before dropping (it may not exist in fresh databases)
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('users')]
    if 'avatar_url' in columns:
        op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('llm_providers', 'name')
    # ### end Alembic commands ###

