"""add_wrapped_api_settings

Revision ID: 40264bad3144
Revises: 19fa42d78025
Create Date: 2025-11-01 09:14:21.247464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40264bad3144'
down_revision: Union[str, None] = '19fa42d78025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: avatar_url column removal is handled separately - do not drop here
    op.add_column('wrapped_api_tools', sa.Column('trigger_condition', sa.Text(), nullable=True))
    op.add_column('wrapped_apis', sa.Column('thinking_mode', sa.String(), nullable=True))
    op.add_column('wrapped_apis', sa.Column('model', sa.String(), nullable=True))
    op.add_column('wrapped_apis', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('wrapped_apis', sa.Column('max_tokens', sa.Integer(), nullable=True))
    op.add_column('wrapped_apis', sa.Column('top_p', sa.Float(), nullable=True))
    op.add_column('wrapped_apis', sa.Column('frequency_penalty', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wrapped_apis', 'frequency_penalty')
    op.drop_column('wrapped_apis', 'top_p')
    op.drop_column('wrapped_apis', 'max_tokens')
    op.drop_column('wrapped_apis', 'temperature')
    op.drop_column('wrapped_apis', 'model')
    op.drop_column('wrapped_apis', 'thinking_mode')
    op.drop_column('wrapped_api_tools', 'trigger_condition')
    # Note: avatar_url column is handled separately - do not add back here
    # ### end Alembic commands ###

