"""add_stripe_fields_to_billing

Revision ID: 9b07c0a3f3f4
Revises: cccf2f65c5b3
Create Date: 2025-11-07 08:46:43.891815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b07c0a3f3f4'
down_revision: Union[str, None] = 'cccf2f65c5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('billing', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('billing', sa.Column('stripe_price_id', sa.String(), nullable=True))
    op.add_column('billing', sa.Column('stripe_current_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('billing', sa.Column('stripe_trial_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('billing', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_billing_stripe_customer_id'), 'billing', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_billing_stripe_subscription_id'), 'billing', ['stripe_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_stripe_subscription_id'), table_name='billing')
    op.drop_index(op.f('ix_billing_stripe_customer_id'), table_name='billing')
    op.drop_column('billing', 'cancelled_at')
    op.drop_column('billing', 'stripe_trial_end')
    op.drop_column('billing', 'stripe_current_period_end')
    op.drop_column('billing', 'stripe_price_id')
    op.drop_column('billing', 'stripe_subscription_id')
    op.drop_column('billing', 'stripe_customer_id')
    # ### end Alembic commands ###

